input InputRegisterOdontologo {
  cedula: String!
  nombres: String!
  apellidos: String!
  ciudad: String!
  direccion: String!
  celular: String!
  email: String!
  especialidad: String!
}

type Odontologo {
  id: Int
  cedula: String!
  nombres: String!
  apellidos: String!
  ciudad: String!
  direccion: String!
  celular: String!
  email: String!
  especialidad: String!
  reclamo: Int
}

type Query {
  getlistUsers: [Odontologo]
  queryUserByCedula(cedula: String!): String
  getDataUser(cedula: String!): Odontologo
}

type Mutation {
  registerUser(InputRegisterOdontologo: InputRegisterOdontologo!): String
  registerUserWin(id: Int!): String
}

type Subscription {
  getLastUser: Odontologo!
  listUsers: [Odontologo]!
  lastUpdate: Odontologo!
}
